'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui';
import { CategorySelector } from './category-selector';
import { useToast } from '@/components/ui/toast';
import { Loader2, ArrowRight } from 'lucide-react';
import type { MeetingCategory } from '@/types/enums';

interface CategorySelectionStepProps {
  meetingId: string;
  projectId: string;
}

export function CategorySelectionStep({
  meetingId,
  projectId,
}: CategorySelectionStepProps) {
  const router = useRouter();
  const supabase = createClient();
  const { showToast } = useToast();

  const [category, setCategory] = useState<MeetingCategory | ''>('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleContinue = async () => {
    if (!category) return;

    setIsSubmitting(true);

    try {
      // Update the meeting with the selected category
      const { error } = await supabase
        .from('meetings')
        .update({ category })
        .eq('id', meetingId);

      if (error) throw error;

      // Refresh the page to trigger processing
      router.refresh();
    } catch (error) {
      console.error('Error updating meeting category:', error);
      showToast('Failed to save category. Please try again.', 'error');
      setIsSubmitting(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="card">
        <p className="mb-6 text-surface-600">
          Choose the category that best describes this meeting. This determines
          what outputs will be generated by the AI analysis.
        </p>

        <CategorySelector value={category} onChange={setCategory} />

        <div className="mt-8 flex justify-end border-t border-surface-200 pt-6">
          <Button
            onClick={handleContinue}
            disabled={!category || isSubmitting}
            isLoading={isSubmitting}
          >
            {isSubmitting ? (
              'Saving...'
            ) : (
              <>
                Continue to Processing
                <ArrowRight className="ml-2 h-4 w-4" />
              </>
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
